GET http://localhost:8080/valid/users/4
###
POST http://localhost:8080/valid/users
Content-Type: application/json

{
  "id": "idTest",
  "pwd": "pwdTest",
  "name": "호애앵",
  "enrollDate": "2024-05-24"
}
